mpo_500:
    left_arm_controller:
        type: position_controllers/JointTrajectoryController
        joints:
           - ur5_left_shoulder_pan_joint
           - ur5_left_shoulder_lift_joint
           - ur5_left_elbow_joint
           - ur5_left_wrist_1_joint
           - ur5_left_wrist_2_joint
           - ur5_left_wrist_3_joint

    left_gripper_controller:
        type: position_controllers/JointTrajectoryController
        joints:
#          - lgripper_robotiq_85_left_knuckle_joint
#          - lgripper_robotiq_85_left_finger_joint
           - ur5_left_l_finger_joint
           - ur5_left_r_finger_joint

    right_arm_controller:
        type: position_controllers/JointTrajectoryController
        joints:
           - ur5_right_shoulder_pan_joint
           - ur5_right_shoulder_lift_joint
           - ur5_right_elbow_joint
           - ur5_right_wrist_1_joint
           - ur5_right_wrist_2_joint
           - ur5_right_wrist_3_joint

    right_gripper_controller:
        type: position_controllers/JointTrajectoryController
        joints:
#           - rgripper_robotiq_85_left_knuckle_joint
#           - rgripper_robotiq_85_left_finger_joint
           - ur5_right_l_finger_joint
           - ur5_right_r_finger_joint
#           - rgripper_finger_joint
        constraints:
            goal_time: 0.6
            stopped_velocity_tolerance: 0.05
            ur5_left_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
            ur5_left_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
            ur5_left_elbow_joint: {trajectory: 0.1, goal: 0.1}
            ur5_left_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
            ur5_left_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
            ur5_left_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
#            lgripper_robotiq_85_left_knuckle_joint: {trajectory: 0.1, goal: 0.1}
#            lgripper_robotiq_85_left_finger_joint: {trajectory: 0.1, goal: 0.1}
            ur5_left_l_finger_joint: {trajectory: 0.1, goal: 0.1}
            ur5_left_r_finger_joint: {trajectory: 0.1, goal: 0.1}
            
            ur5_right_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
            ur5_right_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
            ur5_right_elbow_joint: {trajectory: 0.1, goal: 0.1}
            ur5_right_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
            ur5_right_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
            ur5_right_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
            rgripper_finger_joint: {trajectory: 0.1, goal: 0.1}
#            rgripper_robotiq_85_left_knuckle_joint: {trajectory: 0.1, goal: 0.1}
#            rgripper_robotiq_85_left_finger_joint: {trajectory: 0.1, goal: 0.1}
            ur5_right_l_finger_joint: {trajectory: 0.1, goal: 0.1}
            ur5_right_r_finger_joint: {trajectory: 0.1, goal: 0.1}
  
        stop_trajectory_duration: 0.5
        state_publish_rate:  25
        action_monitor_rate: 10

    wheel_controller:
        type: velocity_controllers/JointTrajectoryController
        joints:
           - mpo_500_omni_wheel_front_left_joint
           - mpo_500_omni_wheel_front_right_joint
           - mpo_500_omni_wheel_back_left_joint
           - mpo_500_omni_wheel_back_right_joint
        gains:
            mpo_500_omni_wheel_front_left_joint:  {p: 100.0, i: 0.01, d: 10.0}
            mpo_500_omni_wheel_front_right_joint: {p: 100.0, i: 0.01, d: 10.0}
            mpo_500_omni_wheel_back_left_joint: {p: 100.0, i: 0.01, d: 10.0}
            mpo_500_omni_wheel_back_right_joint: {p: 100.0, i: 0.01, d: 10.0}


        
