controller_list:
  - name: fake_l_arm_controller
    joints:
      - ur5_left_shoulder_pan_joint
      - ur5_left_shoulder_lift_joint
      - ur5_left_elbow_joint
      - ur5_left_wrist_1_joint
      - ur5_left_wrist_2_joint
      - ur5_left_wrist_3_joint
  - name: fake_l_gripper_controller
    joints:
      - ur5_left_l_finger_joint
      - ur5_left_r_finger_joint
  - name: fake_r_arm_controller
    joints:
      - ur5_right_shoulder_pan_joint
      - ur5_right_shoulder_lift_joint
      - ur5_right_elbow_joint
      - ur5_right_wrist_1_joint
      - ur5_right_wrist_2_joint
      - ur5_right_wrist_3_joint
  - name: fake_r_gripper_controller
    joints:
      - ur5_right_l_finger_joint
      - ur5_right_r_finger_joint
initial:  # Define initial robot poses.
  - group: l_arm
    pose: l_idle
  - group: l_gripper
    pose: l_close
  - group: r_arm
    pose: r_idle
  - group: r_gripper
    pose: r_close