# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: l_arm
  joint_model_group_pose: l_idle
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - mpo_500_omni_wheel_back_left_joint
    - mpo_500_omni_wheel_back_right_joint
    - mpo_500_omni_wheel_front_left_joint
    - mpo_500_omni_wheel_front_right_joint
    - ur5_left_shoulder_pan_joint
    - ur5_left_shoulder_lift_joint
    - ur5_left_elbow_joint
    - ur5_left_wrist_1_joint
    - ur5_left_wrist_2_joint
    - ur5_left_wrist_3_joint
    - ur5_left_l_finger_joint
    - ur5_left_r_finger_joint
    - ur5_right_shoulder_pan_joint
    - ur5_right_shoulder_lift_joint
    - ur5_right_elbow_joint
    - ur5_right_wrist_1_joint
    - ur5_right_wrist_2_joint
    - ur5_right_wrist_3_joint
    - ur5_right_l_finger_joint
    - ur5_right_r_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: mpo_500/left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_left_shoulder_pan_joint
      - ur5_left_shoulder_lift_joint
      - ur5_left_elbow_joint
      - ur5_left_wrist_1_joint
      - ur5_left_wrist_2_joint
      - ur5_left_wrist_3_joint
  - name: mpo_500/left_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_left_l_finger_joint
      - ur5_left_r_finger_joint
  - name: mpo_500/right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_right_shoulder_pan_joint
      - ur5_right_shoulder_lift_joint
      - ur5_right_elbow_joint
      - ur5_right_wrist_1_joint
      - ur5_right_wrist_2_joint
      - ur5_right_wrist_3_joint
  - name: mpo_500/right_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5_right_l_finger_joint
      - ur5_right_r_finger_joint
